[module]
name = "Fish Shell"
description = "Shell interactif moderne avec autocomplétion intelligente"
icon = "🐟"
version = "1.0.0"
author = "Configz"

[installation]
# Type d'installation : "copy", "symlink", "custom"
type = "copy"
# Fonction d'installation personnalisée (optionnelle)
# custom_function = "install_fish_custom"

[paths]
# Chemin relatif dans ~/.config/
target = "fish"
# Fichiers/dossiers à copier (relatif au dossier du module)
sources = ["config.fish"]

[dependencies]
# Paquets système requis (optionnel)
system = ["fish"]
# Autres modules configz requis (optionnel)
modules = []

[post_install]
# Messages à afficher après installation
notes = [
    "Redémarrez votre terminal ou exécutez: exec fish",
    "La configuration Fish est maintenant active",
]
# Commandes à exécuter après installation (optionnel)
# commands = ["fish -c 'echo Configuration chargée'"]

[backup]
# Stratégie de backup : "auto", "manual", "none"
strategy = "auto"
# Fichiers à sauvegarder spécifiquement
files = ["config.fish"]
