[module]
name = "Neovim"
description = "Configuration moderne pour l'éditeur de texte Neovim"
icon = "⚡"
version = "1.0.0"
author = "Configz"

[installation]
# Type d'installation : "copy", "symlink", "custom"
type = "copy"
# Fonction d'installation personnalisée (optionnelle)
# custom_function = "install_nvim_custom"

[paths]
# Chemin relatif dans ~/.config/
target = "nvim"
# Fichiers/dossiers à copier (relatif au dossier du module)
sources = ["init.lua", "lua/"]

[dependencies]
# Paquets système requis (optionnel)
system = ["nvim"]
# Autres modules configz requis (optionnel)
modules = []

[post_install]
# Messages à afficher après installation
notes = [
    "Configuration Neovim installée avec succès",
    "Lancez nvim pour charger la nouvelle configuration",
    "Leader key configurée sur <Espace>",
    "Utilisez :help pour plus d'informations",
]
# Commandes à exécuter après installation (optionnel)
# commands = ["nvim --headless -c 'echo \"Configuration loaded\"' -c 'quit'"]

[backup]
# Stratégie de backup : "auto", "manual", "none"
strategy = "auto"
# Fichiers à sauvegarder spécifiquement
files = ["init.lua", "init.vim"]
directories = ["lua", "plugin", "after"]
