[module]
name = "Ghostty Terminal"
description = "Terminal haute performance avec rendu GPU"
icon = "👻"
version = "1.0.0"
author = "Configz"

[installation]
# Type d'installation : "copy", "symlink", "custom"
type = "copy"
# Fonction d'installation personnalisée (optionnelle)
# custom_function = "install_ghostty_custom"

[paths]
# Chemin relatif dans ~/.config/
target = "ghostty"
# Fichiers/dossiers à copier (relatif au dossier du module)
sources = ["config", "theme/"]

[dependencies]
# Paquets système requis (optionnel)
system = ["ghostty"]
# Autres modules configz requis (optionnel)
modules = []

[post_install]
# Messages à afficher après installation
notes = [
    "Redémarrez Ghostty pour appliquer la configuration",
    "Les thèmes personnalisés sont disponibles dans le menu",
]
# Commandes à exécuter après installation (optionnel)
# commands = []

[backup]
# Stratégie de backup : "auto", "manual", "none"
strategy = "auto"
# Fichiers à sauvegarder spécifiquement
files = ["config"]
directories = ["theme"]
